bg-color = "eff1f5"
border-color = "7c7f93"
text-color = "4c4f69"
tab-text-color = "4c4f69"
hops-table-header-bg-color = "ccd0da"
hops-table-header-text-color = "5c5f77"
hops-table-row-active-text-color = "5c5f77"
hops-table-row-inactive-text-color = "4c4f69"
hops-table-row-active-selected-bg-color = "bcc0cc"
hops-table-row-active-selected-text-color = "4c4f69"
hops-table-row-inactive-selected-bg-color = "bcc0cc"
hops-table-row-inactive-selected-text-color = "4c4f69"
hops-chart-selected-color = "000000"
hops-chart-unselected-color = "8c8fa1"
hops-chart-axis-color = "9ca0b0"
frequency-chart-bar-color = "04a5e5"
frequency-chart-text-color = "eff1f5"
flows-chart-bar-selected-color = "40a02b"
flows-chart-bar-unselected-color = "8c8fa1"
flows-chart-text-current-color = "40a02b"
flows-chart-text-non-current-color = "4c4f69"
samples-chart-color = "40a02b"
samples-chart-lost-color = "d20f39"
help-dialog-bg-color = "e6e9ef"
help-dialog-text-color = "4c4f69"
settings-dialog-bg-color = "e6e9ef"
settings-tab-text-color = "4c4f69"
settings-table-header-text-color = "5c5f77"
settings-table-header-bg-color = "ccd0da"
settings-table-row-text-color = "4c4f69"
map-world-color = "5c5f77"
map-radius-color = "fe640b"
map-selected-color = "40a02b"
map-info-panel-border-color = "7c7f93"
map-info-panel-bg-color = "eff1f5"
map-info-panel-text-color = "4c4f69"
info-bar-bg-color = "ccd0da"
info-bar-text-color = "5c5f77"
