bg-color = "1e1e2e"
border-color = "9399b2"
text-color = "cdd6f4"
tab-text-color = "cdd6f4"
hops-table-header-bg-color = "313244"
hops-table-header-text-color = "bac2de"
hops-table-row-active-text-color = "bac2de"
hops-table-row-inactive-text-color = "cdd6f4"
hops-table-row-active-selected-bg-color = "45475a"
hops-table-row-active-selected-text-color = "cdd6f4"
hops-table-row-inactive-selected-bg-color = "45475a"
hops-table-row-inactive-selected-text-color = "cdd6f4"
hops-chart-selected-color = "a6e3a1"
hops-chart-unselected-color = "7f849c"
hops-chart-axis-color = "6c7086"
frequency-chart-bar-color = "89dceb"
frequency-chart-text-color = "1e1e2e"
flows-chart-bar-selected-color = "a6e3a1"
flows-chart-bar-unselected-color = "7f849c"
flows-chart-text-current-color = "a6e3a1"
flows-chart-text-non-current-color = "cdd6f4"
samples-chart-color = "a6e3a1"
samples-chart-lost-color = "f38ba8"
help-dialog-bg-color = "181825"
help-dialog-text-color = "cdd6f4"
settings-dialog-bg-color = "181825"
settings-tab-text-color = "cdd6f4"
settings-table-header-text-color = "bac2de"
settings-table-header-bg-color = "313244"
settings-table-row-text-color = "cdd6f4"
map-world-color = "9399b2"
map-radius-color = "fab387"
map-selected-color = "a6e3a1"
map-info-panel-border-color = "9399b2"
map-info-panel-bg-color = "1e1e2e"
map-info-panel-text-color = "cdd6f4"
info-bar-bg-color = "313244"
info-bar-text-color = "bac2de"
