bg-color = "24273a"
border-color = "939ab7"
text-color = "cad3f5"
tab-text-color = "cad3f5"
hops-table-header-bg-color = "363a4f"
hops-table-header-text-color = "b8c0e0"
hops-table-row-active-text-color = "b8c0e0"
hops-table-row-inactive-text-color = "cad3f5"
hops-table-row-active-selected-bg-color = "494d64"
hops-table-row-active-selected-text-color = "cad3f5"
hops-table-row-inactive-selected-bg-color = "494d64"
hops-table-row-inactive-selected-text-color = "cad3f5"
hops-chart-selected-color = "a6da95"
hops-chart-unselected-color = "8087a2"
hops-chart-axis-color = "6e738d"
frequency-chart-bar-color = "91d7e3"
frequency-chart-text-color = "24273a"
flows-chart-bar-selected-color = "a6da95"
flows-chart-bar-unselected-color = "8087a2"
flows-chart-text-current-color = "a6da95"
flows-chart-text-non-current-color = "cad3f5"
samples-chart-color = "a6da95"
samples-chart-lost-color = "ed8796"
help-dialog-bg-color = "1e2030"
help-dialog-text-color = "cad3f5"
settings-dialog-bg-color = "1e2030"
settings-tab-text-color = "cad3f5"
settings-table-header-text-color = "b8c0e0"
settings-table-header-bg-color = "363a4f"
settings-table-row-text-color = "cad3f5"
map-world-color = "939ab7"
map-radius-color = "f5a97f"
map-selected-color = "a6da95"
map-info-panel-border-color = "939ab7"
map-info-panel-bg-color = "24273a"
map-info-panel-text-color = "cad3f5"
info-bar-bg-color = "363a4f"
info-bar-text-color = "b8c0e0"
