bg-color = "303446"
border-color = "949cbb"
text-color = "c6d0f5"
tab-text-color = "c6d0f5"
hops-table-header-bg-color = "414559"
hops-table-header-text-color = "b5bfe2"
hops-table-row-active-text-color = "b5bfe2"
hops-table-row-inactive-text-color = "c6d0f5"
hops-table-row-active-selected-bg-color = "51576d"
hops-table-row-active-selected-text-color = "c6d0f5"
hops-table-row-inactive-selected-bg-color = "51576d"
hops-table-row-inactive-selected-text-color = "c6d0f5"
hops-chart-selected-color = "a6d189"
hops-chart-unselected-color = "838ba7"
hops-chart-axis-color = "737994"
frequency-chart-bar-color = "99d1db"
frequency-chart-text-color = "303446"
flows-chart-bar-selected-color = "a6d189"
flows-chart-bar-unselected-color = "838ba7"
flows-chart-text-current-color = "a6d189"
flows-chart-text-non-current-color = "c6d0f5"
samples-chart-color = "a6d189"
samples-chart-lost-color = "e78284"
help-dialog-bg-color = "292c3c"
help-dialog-text-color = "c6d0f5"
settings-dialog-bg-color = "292c3c"
settings-tab-text-color = "c6d0f5"
settings-table-header-text-color = "b5bfe2"
settings-table-header-bg-color = "414559"
settings-table-row-text-color = "c6d0f5"
map-world-color = "949cbb"
map-radius-color = "ef9f76"
map-selected-color = "a6d189"
map-info-panel-border-color = "949cbb"
map-info-panel-bg-color = "303446"
map-info-panel-text-color = "c6d0f5"
info-bar-bg-color = "414559"
info-bar-text-color = "b5bfe2"
