bg-color = "black"
border-color = "gray"
text-color = "gray"
tab-text-color = "green"
hops-table-header-bg-color = "white"
hops-table-header-text-color = "black"
hops-table-row-active-text-color = "gray"
hops-table-row-inactive-text-color = "darkgray"
hops-table-row-active-selected-bg-color = "gray"
hops-table-row-active-selected-text-color = "black"
hops-table-row-inactive-selected-bg-color = "darkgray"
hops-table-row-inactive-selected-text-color = "black"
hops-chart-selected-color = "green"
hops-chart-unselected-color = "gray"
hops-chart-axis-color = "darkgray"
frequency-chart-bar-color = "green"
frequency-chart-text-color = "gray"
flows-chart-bar-selected-color = "green"
flows-chart-bar-unselected-color = "darkgray"
flows-chart-text-current-color = "lightgreen"
flows-chart-text-non-current-color = "white"
samples-chart-color = "yellow"
samples-chart-lost-color = "red"
help-dialog-bg-color = "blue"
help-dialog-text-color = "gray"
settings-dialog-bg-color = "blue"
settings-tab-text-color = "green"
settings-table-header-text-color = "black"
settings-table-header-bg-color = "white"
settings-table-row-text-color = "gray"
map-world-color = "white"
map-radius-color = "yellow"
map-selected-color = "green"
map-info-panel-border-color = "gray"
map-info-panel-bg-color = "black"
map-info-panel-text-color = "gray"
info-bar-bg-color = "white"
info-bar-text-color = "black"
