version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
        - dependency-name: "clap*"
          update-types:
            - "version-update:semver-patch"
        - dependency-name: "serde*"
          update-types:
            - "version-update:semver-patch"
        - dependency-name: "anyhow"
          update-types:
            - "version-update:semver-patch"
        - dependency-name: "thiserror"
          update-types:
            - "version-update:semver-patch"
    allow:
      - dependency-type: "direct"
    open-pull-requests-limit: 10
    rebase-strategy: "disabled"

  # NPM dependencies (docs) - ignore all
  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types:
          - "all"