[licenses]
version = 2
allow = ["Apache-2.0", "MIT", "Unicode-DFS-2016", "ISC", "BSD-2-Clause", "BSD-3-Clause", "WTFPL", "Unicode-3.0", "Zlib"]
confidence-threshold = 0.8
exceptions = []

[advisories]
version = 2
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
ignore = [
  # allow unmaintained paste crate
  { id = "RUSTSEC-2024-0436" },
]
