[licenses]
unlicensed = "deny"
allow = [ "Apache-2.0", "MIT", "Unicode-DFS-2016" ]
copyleft = "deny"
allow-osi-fsf-free = "neither"
default = "deny"
confidence-threshold = 0.8
exceptions = []

[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "deny"
yanked = "warn"
notice = "warn"

# ignores RUSTSEC-2020-0159 (chrono) until fixes are available
ignore = ["RUSTSEC-2020-0071"]