name: trippy
version: 'git'
summary: A network diagnostic tool
description: A network diagnostic tool, inspired by MTR
base: core18
confinement: devmode
parts:
  trippy:
    plugin: rust
    source: .
apps:
  trippy:
    command: bin/trip