name: trippy
version: 'git'
summary: A network diagnostic tool
description: Trippy combines the functionality of traceroute and ping and is designed to assist with the diagnosis of network issues.
base: core18
confinement: strict
parts:
  trippy:
    plugin: rust
    source: .
apps:
  trippy:
    command: bin/trip
    plugs:
      - network-bind
      - network